'use strict';

/**
 * Catalog loading adapter (REQ-10/11, design D5).
 *
 * The extracted catalog is a LOCAL file (generated by tools/extract-catalog.js
 * in the page) — minibia.com serves no catalog.json route, so a same-origin
 * fetch would 404 forever on the real game page. Runtime resolution order:
 *
 *   1. `localStorage['mb-catalog']` FIRST — the extraction seeds it when it
 *      runs in the page (REQ-10). Validated with the same entry normalizer as
 *      the fetch path; corrupt/empty falls through.
 *   2. Same-origin fetch of `catalog.json` as a fallback (kept for future
 *      hosted deployments; works under `@grant none` thanks to CORP
 *      same-origin).
 *   3. When neither is available, log a warning and return the sentinel
 *      `'corrupt'` so the bootstrap can continue in keybind-only mode
 *      (REQ-11).
 *
 * Storage and fetch are injectable so tests never touch a real localStorage
 * or the network:
 *   loadCatalog(url, { fetch, storage, log }) -> entries[] | 'corrupt'
 */

/** localStorage key the extraction seeds (tools/extract-catalog.js, REQ-10). */
const STORAGE_KEY = 'mb-catalog';

/**
 * Normalize raw JSON into catalog entries.
 * @param {*} data - array of entries or {cid: entry} map
 * @returns {Array<object>|null} valid entries, or null when unusable
 */
function normalizeEntries(data) {
  let raw = Array.isArray(data) ? data : data && typeof data === 'object' ? Object.values(data) : null;
  if (!raw) return null;

  const entries = raw
    .filter((e) => e && typeof e === 'object')
    .map((e) => ({
      cid: e.cid ?? e.id ?? null,
      name: typeof e.name === 'string' ? e.name : null,
      article: e.article ?? null,
      type: e.type ?? null,
      weight: e.weight ?? null,
      runeSpellName: e.runeSpellName ?? null,
      imageDataURL: e.imageDataURL ?? e.image ?? null,
      npcTrades: Array.isArray(e.npcTrades) ? e.npcTrades : null,
    }))
    .filter((e) => e.cid !== null && e.cid !== undefined && e.name !== null);

  return entries.length > 0 ? entries : null;
}

/**
 * Read the locally-seeded catalog (the extraction stores it under
 * `mb-catalog`). Returns valid entries, or null when absent/corrupt/empty so
 * the caller falls through to the fetch fallback. Warnings name the failure
 * only when something WAS stored but unusable — absence is silent (the fetch
 * fallback is the expected path on first run).
 *
 * @param {object|null} storage - Storage-like object (localStorage contract)
 * @param {(msg: string) => void} warn - warning sink
 * @returns {Array<object>|null} valid entries, or null to fall through
 */
function readStoredCatalog(storage, warn) {
  if (!storage || typeof storage.getItem !== 'function') return null;
  let raw = null;
  try {
    raw = storage.getItem(STORAGE_KEY);
  } catch (err) {
    warn('catalog: localStorage read failed (' + (err && err.message ? err.message : err) + '); falling back to fetch');
    return null;
  }
  if (raw === null || raw === undefined || raw === '') return null; // absent — silent fall-through
  let data;
  try {
    data = JSON.parse(raw);
  } catch (err) {
    warn('catalog: stored mb-catalog is corrupt JSON (' + (err && err.message ? err.message : err) + '); falling back to fetch');
    return null;
  }
  const entries = normalizeEntries(data);
  if (!entries) {
    warn('catalog: stored mb-catalog has no usable entries; falling back to fetch');
    return null;
  }
  return entries;
}

/**
 * Load the catalog (localStorage seed first, same-origin fetch fallback).
 *
 * @param {string} [url='catalog.json'] - same-origin catalog URL
 * @param {object} [deps]
 * @param {Function} [deps.fetch] - fetch implementation (defaults to globalThis.fetch)
 * @param {object} [deps.storage] - Storage-like object (defaults to globalThis.localStorage)
 * @param {{warn?: Function}} [deps.log] - log sinks
 * @returns {Promise<Array<object>|'corrupt'>} normalized entries, or 'corrupt'
 *   when the catalog is missing/unreadable/invalid (REQ-11 keybind-only mode)
 */
async function loadCatalog(url = 'catalog.json', deps = {}) {
  const { log = {} } = deps;
  const warn = typeof log.warn === 'function' ? log.warn.bind(log) : () => {};
  const fetchImpl = deps.fetch !== undefined ? deps.fetch : globalThis.fetch;
  const storage = deps.storage !== undefined ? deps.storage : globalThis.localStorage;

  const stored = readStoredCatalog(storage, warn);
  if (stored) return stored; // localStorage-first (REQ-10 seed) — no fetch needed

  if (typeof fetchImpl !== 'function') {
    warn('catalog: no fetch available; continuing in keybind-only mode (REQ-11)');
    return 'corrupt';
  }

  let res;
  try {
    res = await fetchImpl(url, { headers: { Accept: 'application/json' } });
  } catch (err) {
    warn(`catalog: fetch failed (${err?.message ?? err}); continuing in keybind-only mode (REQ-11)`);
    return 'corrupt';
  }

  if (!res || typeof res.ok !== 'boolean' || !res.ok) {
    warn(`catalog: HTTP ${res?.status ?? 'unknown'} (missing?); continuing in keybind-only mode (REQ-11)`);
    return 'corrupt';
  }

  let data;
  try {
    data = await res.json();
  } catch (err) {
    warn(`catalog: corrupt JSON (${err?.message ?? err}); continuing in keybind-only mode (REQ-11)`);
    return 'corrupt';
  }

  const entries = normalizeEntries(data);
  if (!entries) {
    warn('catalog: no usable entries (empty or invalid shape); continuing in keybind-only mode (REQ-11)');
    return 'corrupt';
  }

  return entries;
}

module.exports = { loadCatalog, normalizeEntries, readStoredCatalog, STORAGE_KEY };
